services:
  dev-db:
    image: postgres:13
    ports:
      - '5432:5432'
    volumes:
      - dev-db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: nest
    networks:
      - nest
  test-db:
    image: postgres:13
    ports:
      - '5433:5432'

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: nest_test
    networks:
      - nest
networks:
  nest:
volumes:
  dev-db:
